import { Vulnerability } from "./api";

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: "CVE-2024-0001",
    title: "Windows Kernel 远程代码执行漏洞",
    severity: "Critical",
    exploited: "Yes",
    description: "Windows 内核中存在远程代码执行漏洞，攻击者可以通过特制的网络请求执行任意代码。",
    affectedProducts: ["Windows 10", "Windows 11", "Windows Server 2019"],
    publishedDate: "2024-03-15",
    lastUpdated: "2024-03-20",
    kbNumbers: ["KB5025221", "KB5025222"],
    cvssScore: 9.8,
    workarounds: ["禁用相关网络服务", "更新系统到最新版本"],
  },
  {
    id: "CVE-2024-0002",
    title: "Microsoft Exchange Server 权限提升漏洞",
    severity: "Important",
    exploited: "No",
    description: "Exchange Server 中存在权限提升漏洞，本地攻击者可能获得系统管理员权限。",
    affectedProducts: ["Exchange Server 2016", "Exchange Server 2019"],
    publishedDate: "2024-03-10",
    lastUpdated: "2024-03-18",
    kbNumbers: ["KB5025223"],
    cvssScore: 7.5,
    workarounds: ["应用最新安全补丁"],
  },
  {
    id: "CVE-2024-0003",
    title: "Windows Print Spooler 服务漏洞",
    severity: "Critical",
    exploited: "Yes",
    description: "Print Spooler 服务中存在安全漏洞，可能导致远程代码执行。",
    affectedProducts: ["Windows 10", "Windows Server 2019"],
    publishedDate: "2024-03-05",
    lastUpdated: "2024-03-15",
    kbNumbers: ["KB5025224"],
    cvssScore: 9.0,
    workarounds: ["禁用 Print Spooler 服务", "限制访问权限"],
  },
  {
    id: "CVE-2024-0004",
    title: "Microsoft Office 宏安全漏洞",
    severity: "Important",
    exploited: "No",
    description: "Office 文档中的宏可能绕过安全限制，导致任意代码执行。",
    affectedProducts: ["Microsoft Office 2019", "Microsoft 365"],
    publishedDate: "2024-03-01",
    lastUpdated: "2024-03-12",
    kbNumbers: ["KB5025225"],
    cvssScore: 7.8,
    workarounds: ["禁用宏", "使用受保护视图"],
  },
  {
    id: "CVE-2024-0005",
    title: "Windows Defender 绕过漏洞",
    severity: "Low",
    exploited: "No",
    description: "Windows Defender 可能被绕过，导致恶意软件无法被检测。",
    affectedProducts: ["Windows 10", "Windows 11"],
    publishedDate: "2024-02-28",
    lastUpdated: "2024-03-10",
    kbNumbers: ["KB5025226"],
    cvssScore: 4.2,
    workarounds: ["更新病毒库", "启用额外的安全功能"],
  },
  {
    id: "CVE-2024-0006",
    title: "Azure Active Directory 身份验证绕过",
    severity: "Critical",
    exploited: "Yes",
    description: "Azure AD 中存在身份验证绕过漏洞，可能导致未经授权的访问。",
    affectedProducts: ["Azure Active Directory", "Microsoft 365"],
    publishedDate: "2024-02-25",
    lastUpdated: "2024-03-08",
    kbNumbers: ["KB5025227"],
    cvssScore: 9.5,
    workarounds: ["启用多因素认证", "审查访问日志"],
  },
  {
    id: "CVE-2024-0007",
    title: "SQL Server 数据库注入漏洞",
    severity: "Important",
    exploited: "Yes",
    description: "SQL Server 中存在 SQL 注入漏洞，可能导致数据泄露或未授权数据访问。",
    affectedProducts: ["SQL Server 2019", "SQL Server 2022"],
    publishedDate: "2024-02-20",
    lastUpdated: "2024-03-05",
    kbNumbers: ["KB5025228"],
    cvssScore: 8.2,
    workarounds: ["使用参数化查询", "限制数据库用户权限"],
  },
  {
    id: "CVE-2024-0008",
    title: "SharePoint Server 跨站脚本漏洞",
    severity: "Low",
    exploited: "No",
    description: "SharePoint 页面中存在 XSS 漏洞，可能导致用户会话被劫持。",
    affectedProducts: ["SharePoint Server 2019", "SharePoint Online"],
    publishedDate: "2024-02-15",
    lastUpdated: "2024-02-28",
    kbNumbers: ["KB5025229"],
    cvssScore: 4.8,
    workarounds: ["启用内容安全策略", "更新到最新版本"],
  },
  {
    id: "CVE-2024-0009",
    title: "Windows DNS 服务器缓存投毒漏洞",
    severity: "Critical",
    exploited: "No",
    description: "Windows DNS 服务器存在缓存投毒漏洞，可能导致 DNS 解析被劫持。",
    affectedProducts: ["Windows Server 2019", "Windows Server 2022"],
    publishedDate: "2024-02-10",
    lastUpdated: "2024-02-25",
    kbNumbers: ["KB5025230"],
    cvssScore: 8.9,
    workarounds: ["启用 DNSSEC", "配置 DNS 安全扩展"],
  },
  {
    id: "CVE-2024-0010",
    title: "Microsoft Teams 远程代码执行",
    severity: "Important",
    exploited: "No",
    description: "Teams 客户端存在远程代码执行漏洞，通过特制消息可能触发。",
    affectedProducts: ["Microsoft Teams", "Microsoft 365"],
    publishedDate: "2024-02-05",
    lastUpdated: "2024-02-20",
    kbNumbers: ["KB5025231"],
    cvssScore: 7.9,
    workarounds: ["更新客户端", "限制文件共享权限"],
  },
  {
    id: "CVE-2024-0011",
    title: "Windows Hello 生物识别绕过",
    severity: "Important",
    exploited: "Yes",
    description: "Windows Hello 生物识别认证存在绕过漏洞，可能导致未授权登录。",
    affectedProducts: ["Windows 10", "Windows 11"],
    publishedDate: "2024-02-01",
    lastUpdated: "2024-02-15",
    kbNumbers: ["KB5025232"],
    cvssScore: 7.4,
    workarounds: ["禁用生物识别登录", "使用强密码认证"],
  },
  {
    id: "CVE-2024-0012",
    title: "Edge 浏览器沙箱逃逸漏洞",
    severity: "Critical",
    exploited: "No",
    description: "Microsoft Edge 浏览器沙箱存在逃逸漏洞，可能导致本地代码执行。",
    affectedProducts: ["Microsoft Edge"],
    publishedDate: "2024-01-28",
    lastUpdated: "2024-02-10",
    kbNumbers: ["KB5025233"],
    cvssScore: 9.1,
    workarounds: ["启用网站隔离", "禁用不信任的扩展"],
  }
]; 